version: '3'

services:
  spring-deploy:
    build: spring-deploy
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - APP_MESSAGE:"Hola mundo desde prod"
    restart: always
  